// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: itmdg5kTwTPM7Z7CWx2NER
// Component: bWoJdglL_8

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_plasmic_test.module.css"; // plasmic-import: itmdg5kTwTPM7Z7CWx2NER/projectcss
import sty from "./PlasmicBomBomItes.module.css"; // plasmic-import: bWoJdglL_8/css

export type PlasmicBomBomItes__VariantMembers = {};
export type PlasmicBomBomItes__VariantsArgs = {};
type VariantPropType = keyof PlasmicBomBomItes__VariantsArgs;
export const PlasmicBomBomItes__VariantProps = new Array<VariantPropType>();

export type PlasmicBomBomItes__ArgsType = {};
type ArgPropType = keyof PlasmicBomBomItes__ArgsType;
export const PlasmicBomBomItes__ArgProps = new Array<ArgPropType>();

export type PlasmicBomBomItes__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultBomBomItesProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicBomBomItes__RenderFunc(props: {
  variants: PlasmicBomBomItes__VariantsArgs;
  args: PlasmicBomBomItes__ArgsType;
  overrides: PlasmicBomBomItes__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBomBomItes__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBomBomItes__VariantsArgs;
    args?: PlasmicBomBomItes__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBomBomItes__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicBomBomItes__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicBomBomItes__ArgProps,
          internalVariantPropNames: PlasmicBomBomItes__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBomBomItes__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBomBomItes";
  } else {
    func.displayName = `PlasmicBomBomItes.${nodeName}`;
  }
  return func;
}

export const PlasmicBomBomItes = Object.assign(
  // Top-level PlasmicBomBomItes renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicBomBomItes
    internalVariantProps: PlasmicBomBomItes__VariantProps,
    internalArgProps: PlasmicBomBomItes__ArgProps
  }
);

export default PlasmicBomBomItes;
/* prettier-ignore-end */
